micronaut:
  application:
    name: lojaService
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3
kafka:
  booststrap:
    servers: localhost:9092
consul:
  client:
    registration:
      enable: true
    defaltZone: "localhost:8500"